"""FastAPI routes for the ASC platform."""

from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect
from typing import Optional
import json
import asyncio

from app.models.schemas import (
    WorkflowRequest, WorkflowStatus, WorkflowGraph,
    CostMetrics, DeploymentStatus, MemoryEntry, MemoryType,
)
from app.workflow.engine import workflow_engine
from app.memory.memory_system import memory_system

router = APIRouter(prefix="/api/v1")


# ─── Workflow Endpoints ──────────────────────────────────────────────────────

@router.post("/workflows", response_model=WorkflowStatus)
async def create_workflow(request: WorkflowRequest):
    """Start a new software development workflow."""
    try:
        return await workflow_engine.start_workflow(
            user_prompt=request.user_prompt,
            mode=request.mode,
            project_name=request.project_name,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/workflows/{workflow_id}", response_model=WorkflowStatus)
async def get_workflow(workflow_id: str):
    """Get the status of a workflow."""
    try:
        return await workflow_engine.get_workflow_status(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.post("/workflows/{workflow_id}/approve", response_model=WorkflowStatus)
async def approve_workflow(workflow_id: str):
    """Approve a workflow that's waiting for human approval."""
    try:
        return await workflow_engine.approve_workflow(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/workflows/{workflow_id}/graph", response_model=WorkflowGraph)
async def get_workflow_graph(workflow_id: str):
    """Get the workflow execution DAG."""
    try:
        return await workflow_engine.get_workflow_graph(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/workflows/{workflow_id}/outputs")
async def get_workflow_outputs(workflow_id: str):
    """Get all outputs generated by the workflow."""
    wf = workflow_engine.workflows.get(workflow_id)
    if not wf:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return {"outputs": wf.get("outputs", {})}


# ─── Agent Endpoints ─────────────────────────────────────────────────────────

@router.get("/agents")
async def get_all_agents():
    """Get the status of all agents."""
    return await workflow_engine.get_all_agent_statuses()


# ─── Memory Endpoints ────────────────────────────────────────────────────────

@router.post("/memory/search")
async def search_memory(query: str, memory_type: Optional[str] = None):
    """Search through memory."""
    mt = MemoryType(memory_type) if memory_type else None
    results = await memory_system.recall(query, mt)
    return {
        "results": [
            {
                "id": r.id,
                "type": r.memory_type.value,
                "content": r.content[:200],
                "importance": r.importance,
                "tags": r.tags,
                "timestamp": r.timestamp.isoformat(),
            }
            for r in results
        ]
    }


@router.get("/memory/stats")
async def get_memory_stats():
    """Get memory system statistics."""
    return await memory_system.get_stats()


# ─── Dashboard Endpoints ─────────────────────────────────────────────────────

@router.get("/dashboard/agents")
async def dashboard_agents():
    """Get agent statuses for the dashboard."""
    return await workflow_engine.get_all_agent_statuses()


@router.get("/dashboard/workflows")
async def dashboard_workflows():
    """Get all workflow summaries for the dashboard."""
    return [
        {
            "id": wf["id"],
            "project_name": wf["project_name"],
            "status": wf["state"].value,
            "progress": wf["progress"],
            "current_agent": wf.get("current_agent"),
            "created_at": wf["created_at"].isoformat(),
            "updated_at": wf["updated_at"].isoformat(),
        }
        for wf in workflow_engine.workflows.values()
    ]


@router.get("/dashboard/costs")
async def dashboard_costs():
    """Get cost metrics for the dashboard."""
    total_tokens = sum(
        cm.total_tokens for cm in workflow_engine.cost_metrics.values()
    )
    total_cost = sum(
        cm.total_cost for cm in workflow_engine.cost_metrics.values()
    )
    return {
        "total_tokens": total_tokens,
        "total_cost": total_cost,
        "workflow_count": len(workflow_engine.workflows),
    }


@router.get("/dashboard/deployment")
async def dashboard_deployment():
    """Get deployment status for the dashboard."""
    return {
        "build_status": "idle",
        "production_url": None,
        "staging_url": None,
        "health": "healthy",
        "last_deployed": None,
        "rollback_available": False,
    }


# ─── Health Check ────────────────────────────────────────────────────────────

@router.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "version": "1.0.0",
        "workflows_active": sum(
            1 for wf in workflow_engine.workflows.values()
            if wf["state"].value in ("running", "waiting_approval")
        ),
    }


# ─── WebSocket for real-time updates ─────────────────────────────────────────

@router.websocket("/ws/{workflow_id}")
async def websocket_endpoint(websocket: WebSocket, workflow_id: str):
    """WebSocket endpoint for real-time workflow updates."""
    await websocket.accept()
    try:
        while True:
            wf = workflow_engine.workflows.get(workflow_id)
            if wf:
                await websocket.send_json({
                    "status": wf["state"].value,
                    "progress": wf["progress"],
                    "current_agent": wf.get("current_agent"),
                    "messages": [
                        {
                            "from": m.from_agent.value,
                            "type": m.message_type.value,
                            "content": m.content[:200],
                            "timestamp": m.timestamp.isoformat(),
                        }
                        for m in workflow_engine.messages.get(workflow_id, [])[-5:]
                    ],
                })
            await asyncio.sleep(1)
    except WebSocketDisconnect:
        pass