"""FastAPI routes for the ASC platform."""

from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect, Depends
from pydantic import BaseModel
from typing import Optional
import json
import asyncio

from app.models.schemas import (
    WorkflowRequest, WorkflowStatus, WorkflowGraph,
    CostMetrics, DeploymentStatus, MemoryEntry, MemoryType,
    UserCreate, UserLogin, UserResponse, Token,
)
from app.workflow.engine import workflow_engine
from app.memory.memory_system import memory_system
from app.core import users as user_store
from app.core.security import create_access_token
from app.api.deps import get_current_user

router = APIRouter(prefix="/api/v1")


# ─── Authentication Endpoints ────────────────────────────────────────────────

@router.post("/auth/register", response_model=UserResponse, status_code=201)
async def register(payload: UserCreate):
    """Register a new user account."""
    if not payload.email or not payload.password:
        raise HTTPException(status_code=422, detail="Email and password are required")
    try:
        user = await user_store.create_user(
            email=payload.email,
            password=payload.password,
            full_name=payload.full_name,
        )
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
    return UserResponse(
        id=user["id"],
        email=user["email"],
        full_name=user.get("full_name"),
        is_active=user.get("is_active", True),
    )


@router.post("/auth/login", response_model=Token)
async def login(payload: UserLogin):
    """Authenticate and return a JWT access token."""
    user = await user_store.authenticate_user(payload.email, payload.password)
    if user is None:
        raise HTTPException(status_code=401, detail="Incorrect email or password")
    token = create_access_token({"sub": user["email"]})
    return Token(access_token=token)


@router.get("/auth/me", response_model=UserResponse)
async def me(current_user: UserResponse = Depends(get_current_user)):
    """Return the currently authenticated user."""
    return current_user


# ─── Workflow Endpoints ──────────────────────────────────────────────────────

@router.post("/workflows", response_model=WorkflowStatus)
async def create_workflow(
    request: WorkflowRequest,
    current_user: UserResponse = Depends(get_current_user),
):
    """Start a new software development workflow."""
    try:
        return await workflow_engine.start_workflow(
            user_prompt=request.user_prompt,
            mode=request.mode,
            project_name=request.project_name,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/workflows/{workflow_id}", response_model=WorkflowStatus)
async def get_workflow(workflow_id: str):
    """Get the status of a workflow."""
    try:
        return await workflow_engine.get_workflow_status(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.post("/workflows/{workflow_id}/approve", response_model=WorkflowStatus)
async def approve_workflow(
    workflow_id: str,
    current_user: UserResponse = Depends(get_current_user),
):
    """Approve a workflow that's waiting for human approval."""
    try:
        return await workflow_engine.approve_workflow(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/workflows/background")
async def create_background_workflow(
    request: WorkflowRequest,
    current_user: UserResponse = Depends(get_current_user),
):
    """Enqueue an autonomous workflow to run in a Celery worker.

    Returns a Celery task id. The worker persists results to the database.
    Best suited for autonomous mode (approval mode would pause for input).
    """
    try:
        from app.tasks.workflow_tasks import run_workflow_task

        async_result = run_workflow_task.delay(
            user_prompt=request.user_prompt,
            mode=request.mode.value,
            project_name=request.project_name,
        )
        return {"task_id": async_result.id, "status": "queued"}
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Task queue unavailable: {e}")


@router.get("/workflows/{workflow_id}/graph", response_model=WorkflowGraph)
async def get_workflow_graph(workflow_id: str):
    """Get the workflow execution DAG."""
    try:
        return await workflow_engine.get_workflow_graph(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/workflows/{workflow_id}/outputs")
async def get_workflow_outputs(workflow_id: str):
    """Get all outputs generated by the workflow."""
    wf = workflow_engine.workflows.get(workflow_id)
    if not wf:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return {"outputs": wf.get("outputs", {})}


@router.get("/workflows/{workflow_id}/messages")
async def get_workflow_messages(workflow_id: str):
    """Get the agent conversation transcript for a workflow."""
    try:
        status = await workflow_engine.get_workflow_status(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    return {
        "workflow_id": workflow_id,
        "status": status.status,
        "messages": [
            {
                "id": m.id,
                "from": m.from_agent.value if m.from_agent else None,
                "to": m.to_agent.value if m.to_agent else None,
                "type": m.message_type.value,
                "content": m.content,
                "timestamp": m.timestamp.isoformat(),
            }
            for m in status.messages
        ],
    }


# ─── Agent Endpoints ─────────────────────────────────────────────────────────

@router.get("/agents")
async def get_all_agents():
    """Get the status of all agents."""
    return await workflow_engine.get_all_agent_statuses()


# ─── Memory Endpoints ────────────────────────────────────────────────────────

class MemorySearchRequest(BaseModel):
    query: str
    memory_type: Optional[str] = None
    semantic: bool = False


@router.post("/memory/search")
async def search_memory(req: MemorySearchRequest):
    """Search through memory (substring by default, or semantic ranking)."""
    mt = MemoryType(req.memory_type) if req.memory_type else None
    results = await memory_system.recall(req.query, mt, semantic=req.semantic)
    return {
        "results": [
            {
                "id": r.id,
                "type": r.memory_type.value,
                "content": r.content[:200],
                "importance": r.importance,
                "tags": r.tags,
                "timestamp": r.timestamp.isoformat(),
            }
            for r in results
        ]
    }


@router.get("/memory/stats")
async def get_memory_stats():
    """Get memory system statistics."""
    return await memory_system.get_stats()


@router.get("/memory/related/{memory_id}")
async def get_related_memories(memory_id: str, limit: int = 20):
    """Get memories related to the given one (knowledge-graph traversal)."""
    related = await memory_system.related(memory_id, limit=limit)
    # Resolve related ids back to full entries for the UI.
    all_entries = (
        list(memory_system._backend._stores["working"].values())
        + list(memory_system._backend._stores["session"].values())
        + list(memory_system._backend._stores["project"].values())
        + list(memory_system._backend._stores["organization"].values())
        + list(memory_system._backend._stores["long_term"].values())
    )
    by_id = {e.id: e for e in all_entries}
    return {
        "id": memory_id,
        "related": [
            {
                "id": r_id,
                "type": by_id[r_id].memory_type.value,
                "content": by_id[r_id].content[:200],
                "importance": by_id[r_id].importance,
            }
            for r_id in related
            if r_id in by_id
        ],
    }


# ─── Dashboard Endpoints ─────────────────────────────────────────────────────

@router.get("/dashboard/agents")
async def dashboard_agents():
    """Get agent statuses for the dashboard."""
    return await workflow_engine.get_all_agent_statuses()


@router.get("/dashboard/workflows")
async def dashboard_workflows():
    """Get all workflow summaries for the dashboard."""
    return [
        {
            "id": wf["id"],
            "project_name": wf["project_name"],
            "status": wf["state"].value,
            "progress": wf["progress"],
            "current_agent": wf.get("current_agent"),
            "created_at": wf["created_at"].isoformat(),
            "updated_at": wf["updated_at"].isoformat(),
        }
        for wf in workflow_engine.workflows.values()
    ]


@router.get("/dashboard/costs")
async def dashboard_costs():
    """Get cost metrics for the dashboard."""
    total_tokens = sum(
        cm.total_tokens for cm in workflow_engine.cost_metrics.values()
    )
    total_cost = sum(
        cm.total_cost for cm in workflow_engine.cost_metrics.values()
    )
    total_calls = sum(
        cm.api_calls for cm in workflow_engine.cost_metrics.values()
    )
    # Aggregate per-agent usage across all workflows.
    by_agent: dict[str, dict] = {}
    for cm in workflow_engine.cost_metrics.values():
        for role, stats in cm.by_agent.items():
            agg = by_agent.setdefault(role, {"tokens": 0, "cost": 0.0, "calls": 0})
            agg["tokens"] += stats.get("tokens", 0)
            agg["cost"] += stats.get("cost", 0.0)
            agg["calls"] += stats.get("calls", 0)
    return {
        "total_tokens": total_tokens,
        "total_cost": round(total_cost, 6),
        "api_calls": total_calls,
        "workflow_count": len(workflow_engine.workflows),
        "by_agent": by_agent,
    }


@router.get("/dashboard/deployment")
async def dashboard_deployment():
    """Get deployment status for the dashboard."""
    return {
        "build_status": "idle",
        "production_url": None,
        "staging_url": None,
        "health": "healthy",
        "last_deployed": None,
        "rollback_available": False,
    }


# ─── Health Check ────────────────────────────────────────────────────────────

@router.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "version": "1.0.0",
        "workflows_active": sum(
            1 for wf in workflow_engine.workflows.values()
            if wf["state"].value in ("running", "waiting_approval")
        ),
    }


# ─── WebSocket for real-time updates ─────────────────────────────────────────

@router.websocket("/ws/{workflow_id}")
async def websocket_endpoint(websocket: WebSocket, workflow_id: str):
    """WebSocket endpoint for real-time workflow updates."""
    await websocket.accept()
    try:
        while True:
            wf = workflow_engine.workflows.get(workflow_id)
            if wf:
                await websocket.send_json({
                    "status": wf["state"].value,
                    "progress": wf["progress"],
                    "current_agent": wf.get("current_agent"),
                    "messages": [
                        {
                            "from": m.from_agent.value,
                            "type": m.message_type.value,
                            "content": m.content[:200],
                            "timestamp": m.timestamp.isoformat(),
                        }
                        for m in workflow_engine.messages.get(workflow_id, [])[-5:]
                    ],
                })
            await asyncio.sleep(1)
    except WebSocketDisconnect:
        pass